### ISSUE TITLE
progress: Crash with latest source

### ISSUE THREAD

**Issue by sjg20** [fwupd/fwupd#4749]
I am not sure how to use progress anymore. Are the docs at the top of fu-progress.c correct?

There have been some API changes but I am not sure how to change my plugin.

**fwupd version information**
based on:

bb2ea8247 (us/main) trivial: validate packages exist before installing in helper script

c6d61eb38 (HEAD -> sim2) review update 2
d246c194d review updates
61fedc0ed vbe: Add documentation
d24c8b6db vbe: Add an example showing how to build an update
6e4d9b124 vbe: Add a device for VBE simple
b2bcfbc7e vbe: Add the plugin
e78b1955c vbe: Bring vbe into the build
87acf9cd8 vbe: Add a library for accessing Flat Image Trees
91dc3ac4b trvial: Update .gitignore for example files

```shell
sudo build/src/fwupdmgr --version
runtime   org.freedesktop.fwupd         1.7.5
runtime   com.dell.libsmbios            2.4
compile   org.freedesktop.gusb          0.3.4
runtime   org.kernel                    5.4.0-113-generic
compile   org.freedesktop.fwupd         1.7.5
runtime   org.freedesktop.gusb          0.3.4
```

Log:

10:08:22:0958 FuDebug              Verbose debugging enabled (on console 1)
Loading…                 [-                                      ]10:08:22:0959 FuMain               locked /run/lock/fwupdtool
10:08:22:0963 FuMain               Failed to stop daemon: failed to find fwupd.service: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit fwupd.service not loaded.
10:08:22:0964 FuConfig             trying to load config values from /usr/local/etc/fwupd/daemon.conf
10:08:22:0964 FuConfig             trying to load config values from /var/local/etc/fwupd/daemon.conf
10:08:22:0964 FuConfig             using autodetected max archive size 18.4 EB
10:08:22:0964 FuConfig             failed to read UpdateMotd key: Key file does not have group “fwupd”
10:08:22:0964 FuConfig             failed to read EnumerateAllDevices key: Key file does not have group “fwupd”
10:08:22:0964 FuConfig             failed to read IgnorePower key: Key file does not have group “fwupd”
10:08:22:0964 FuConfig             failed to read OnlyTrusted key: Key file does not have group “fwupd”
10:08:22:0964 FuConfig             failed to read ShowDevicePrivate key: Key file does not have group “fwupd”
10:08:22:0972 GLib-GIO             _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Loading…                 [ -                                     ]10:08:22:0972 XbSilo               attempting to load /var/local/cache/fwupd/metainfo.xmlb
10:08:22:0972 XbSilo               file: d609e29a-fb78-8dbf-83c3-9bed8a922fce, current:d609e29a-fb78-8dbf-83c3-9bed8a922fce, cached: (null)
10:08:22:0972 XbSilo               loading silo with file contents
10:08:22:0972 FuRemoteList         path /usr/local/etc/fwupd/remotes.d does not exist
10:08:22:0973 Jcat                 reading /var/local/lib/fwupd/pki/secret.key with 2455 bytes
10:08:22:0973 Jcat                 reading /var/local/lib/fwupd/pki/client.pem with 1383 bytes
10:08:22:0981 FuEngine             client certificate exists and working
Loading…                 [                                       ]10:08:22:0981 FuHistory            trying to open database '/var/local/lib/fwupd/pending.db'
10:08:22:0981 FuHistory            got schema version of 7
Loading…                 [                                       ]10:08:22:0987 FuQuirks             loading quirks from /usr/local/share/fwupd/quirks.d
10:08:22:0987 FuQuirks             loading quirks from /var/local/lib/fwupd/quirks.d
10:08:22:0987 XbSilo               attempting to load /var/local/cache/fwupd/quirks.xmlb
10:08:22:0987 XbSilo               file: 00000000-0000-0000-0000-000000000000, current:00000000-0000-0000-0000-000000000000, cached: (null)
10:08:22:0987 XbSilo               loading silo with file contents
10:08:22:0987 FuQuirks             no quirk data, not creating prepared queries
10:08:22:0987 FuSmbios             trying to read /sys/class/dmi/id
10:08:22:0988 FuHwids              not loading HwId overrides from /usr/local/etc/fwupd/daemon.conf
10:08:22:0988 FuHwids              not loading HwId overrides from /var/local/lib/fwupd/daemon.conf
10:08:22:0988 FuHwids              smbios property Manufacturer=System manufacturer
10:08:22:0988 FuHwids              smbios property EnclosureKind=3
10:08:22:0988 FuHwids              smbios property Family=To be filled by O.E.M.
10:08:22:0988 FuHwids              smbios property ProductName=System Product Name
10:08:22:0988 FuHwids              smbios property ProductSku=SKU
10:08:22:0988 FuHwids              smbios property BiosVendor=American Megatrends Inc.
10:08:22:0988 FuHwids              smbios property BiosVersion=1203
10:08:22:0988 FuHwids              smbios property BiosMajorRelease=05
10:08:22:0988 FuHwids              smbios property BiosMinorRelease=0d
10:08:22:0988 FuHwids              smbios property FirmwareMajorRelease=ff
10:08:22:0988 FuHwids              smbios property FirmwareMinorRelease=ff
10:08:22:0988 FuHwids              smbios property BaseboardManufacturer=ASUSTeK COMPUTER INC.
10:08:22:0988 FuHwids              smbios property BaseboardProduct=PRIME X399-A
Loading…                 [*                                      ]10:08:22:0988 FuEngine             ignoring: Error opening directory “/var/local/lib/fwupd/local.d”: No such file or directory
10:08:22:0988 FuEngine             ignoring: Error opening directory “/usr/local/share/fwupd/local.d”: No such file or directory
10:08:22:0988 XbSilo               attempting to load /var/local/cache/fwupd/metadata.xmlb
10:08:22:0988 XbSilo               file: 00000000-0000-0000-0000-000000000000, current:00000000-0000-0000-0000-000000000000, cached: (null)
10:08:22:0988 XbSilo               loading silo with file contents
[New Thread 0x7ffff216e700 (LWP 2343958)]
[New Thread 0x7ffff196d700 (LWP 2343959)]
[New Thread 0x7ffff116c700 (LWP 2343960)]
10:08:24:0495 FuEngine             failed to setup backend bluez: Operation was cancelled
Loading…                 [*                                      ]10:08:24:0495 FuPlugin             init(vbe)
Loading…                 [*                                      ]10:08:24:0495 FuContext            battery threshold now 10
Loading…                 [ -                                     ]10:08:24:0496 FuPlugin             startup(vbe)
10:08:24:0496 Vbe                  Running tests

10:08:24:0496 Vbe                  Processing system DT '/var/local/lib/fwupd/vbe/system.dtb'
10:08:24:0496 Vbe                  Update mechanism: simple
10:08:24:0496 Vbe                  VBE update methods: 1
Loading…                 [*                                      ]10:08:24:0496 FuPlugin             coldplug(vbe)
10:08:24:0496 FuDevice             using 0f7d0d088b6ea936fb25b477722d734706fe8b40 for simple
10:08:24:0496 FuDevice             changing verfmt for 0f7d0d088b6ea936fb25b477722d734706fe8b40: pair->triplet
10:08:24:0496 FuDevice             converted '2022.01' to '0.2022.01'
10:08:24:0496 FuPlugin             emit added from vbe: 0f7d0d088b6ea936fb25b477722d734706fe8b40
10:08:24:0497 FuDeviceList         ::added 0f7d0d088b6ea936fb25b477722d734706fe8b40
10:08:24:0497 FuMain               ADDED:
FuVbeSimpleDevice:
  DeviceId:             0f7d0d088b6ea936fb25b477722d734706fe8b40
  Name:                 simple
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware ⚠
  Guid:                 bb3b05a8-ebef-11ec-be98-d3a15278be95
  Plugin:               vbe
  Protocol:             org.vbe
  Flags:                internal|updatable|registered|needs-reboot|can-verify|can-verify-image
  Vendor:               U-Boot
  VendorId:             VBE:U-Boot
  Version:              1.2.3
  VersionLowest:        0.0.1
  VersionBootloader:    0.2022.01
  VersionFormat:        triplet
  Icon:                 computer
  Created:              2022-06-16
  PhysicalId:           vbe
  InternalFlags:        ensure-semver|md-set-signed

Authenticating…          [**                                     ]10:08:24:0497 FuEngine             using plugins: vbe
Unknown                  [**                                     ]
Loading…                 [*******************                    ]10:08:24:0500 FuEngine             service restarted, but no reboot has taken place
10:08:24:0500 FuEngine             inheriting needs-reboot for simple
Unknown                  [-                                      ]
10:08:24:0500 FuEngine             writing motd target /var/local/cache/fwupd/motd.d/85-fwupd
WARNING: This package has not been validated, it may not work properly.
Writing…                 [*******************                    ]Selected device: simple
10:08:24:0500 FuCommon             reading plugins/vbe/example/Vbe-Board-1.2.4.cab with 3018 bytes
Decompressing…           [-                                      ]10:08:24:0505 FuCabinet            failed to verify com.Vbe.Board.metainfo.xml: no JcatItem
10:08:24:0505 FuCabinet            processing file: com.Vbe.Board.metainfo.xml
10:08:24:0505 XbSilo               compiling 30c57752aeb48d7e5c61bbd6ed38e15254c1647e:filename=com.Vbe.Board.metainfo.xml:prefix=components…
10:08:24:0505 FuCabinet            processing release: 1.2.4
10:08:24:0505 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
10:08:24:0505 FuEngine             requirement 1.0.1 ge 1.8.2 -> org.freedesktop.fwupd passed
10:08:24:0505 FuEngine             requirement 1.0.1 ge 1.8.2 -> org.freedesktop.fwupd passed
10:08:24:0506 FuIdle               inhibiting: update
10:08:24:0506 FuEngine             composite update 1: 0f7d0d088b6ea936fb25b477722d734706fe8b40
bad
10:08:24:0506 FuProgress           fu_progress_set_steps: assertion 'priv->id != NULL' failed
10:08:24:0506 FuProgress           fu_progress_get_child: assertion 'priv->id != NULL' failed
10:08:24:0506 FuEngine             fu_engine_install_release: assertion 'FU_IS_PROGRESS(progress)' failed
10:08:24:0506 FuIdle               uninhibiting: update

Thread 1 "fwupdtool" received signal SIGSEGV, Segmentation fault.
main (argc=4, argv=0x7fffffffe9c8) at ../src/fu-tool.c:3966
3966			g_printerr("%s\n", error->message);

**Comment by sjg20** [comment]
sudo G_DEBUG=fatal-criticals gdb-multiarch --args build/src/fwupdtool --verbose install plugins/vbe/example/Vbe-Board-1.2.4.cab bb3b05a8-ebef-11ec-be98-d3a15278be95

This actually gives a crash on the progress assert, but it could be the root cause.

...
Decompressing…           [-                                      ]14:56:24:0179 FuCabinet            failed to verify com.Vbe.Board.metainfo.xml: no JcatItem
14:56:24:0179 FuCabinet            processing file: com.Vbe.Board.metainfo.xml
14:56:24:0179 XbSilo               compiling 30c57752aeb48d7e5c61bbd6ed38e15254c1647e:filename=com.Vbe.Board.metainfo.xml:prefix=components…
14:56:24:0179 FuCabinet            processing release: 1.2.4
14:56:24:0179 XbSilo               ignoring for OR statement: element name suggests is unknown in silo
14:56:24:0179 FuEngine             requirement 1.0.1 ge 1.8.2 -> org.freedesktop.fwupd passed
14:56:24:0179 FuEngine             requirement 1.0.1 ge 1.8.2 -> org.freedesktop.fwupd passed
14:56:24:0179 FuIdle               inhibiting: update
14:56:24:0179 FuEngine             composite update 1: 0f7d0d088b6ea936fb25b477722d734706fe8b40
14:56:24:0179 FuProgress           fu_progress_set_steps: assertion 'priv->id != NULL' failed

Thread 1 "fwupdtool" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7b78295 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) where
#0  0x00007ffff7b78295 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7b79579 in g_logv () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7b79743 in g_log () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7f250a8 in fu_progress_set_steps (self=0x7fffe400a510, step_max=1)
    at ../libfwupdplugin/fu-progress.c:543
#4  0x000055555559233e in fu_engine_install_releases
    (self=0x555555632040, request=0x55555560e600, releases=0x5555556c12e0, blob_cab=0x7fffe800f240, progress=0x7fffe400a510, flags=FWUPD_INSTALL_FLAG_NONE, error=0x7fffffffe468) at ../src/fu-engine.c:2055
#5  0x0000555555575876 in fu_util_install
    (priv=0x55555560b520, values=0x55555563c6f0, error=0x7fffffffe468) at ../src/fu-tool.c:1412
#6  0x000055555557f99a in fu_util_cmd_array_run
    (array=0x55555560b600, priv=0x55555560b520, command=0x7fffffffec65 "install", values=0x7fffffffe9a8, error=0x7fffffffe468) at ../src/fu-util-common.c:632
#7  0x000055555557c98c in main (argc=4, argv=0x7fffffffe998) at ../src/fu-tool.c:3957



note: with just gdb I get:

14:55:57:0951 FuIdle               inhibiting: update
14:55:57:0951 FuEngine             composite update 1: 0f7d0d088b6ea936fb25b477722d734706fe8b40
14:55:57:0951 FuProgress           fu_progress_set_steps: assertion 'priv->id != NULL' failed
14:55:57:0951 FuProgress           fu_progress_get_child: assertion 'priv->id != NULL' failed
14:55:57:0951 FuEngine             fu_engine_install_release: assertion 'FU_IS_PROGRESS(progress)' failed
14:55:57:0952 FuIdle               uninhibiting: update

Thread 1 "fwupdtool" received signal SIGSEGV, Segmentation fault.
main (argc=4, argv=0x7fffffffe9c8) at ../src/fu-tool.c:3966
3966			g_printerr("%s\n", error->message);
(gdb) where
#0  main (argc=4, argv=0x7fffffffe9c8) at ../src/fu-tool.c:3966
(gdb) q
A debugging session is active.

	Inferior 1 [process 2390929] will be killed.
