### ISSUE TITLE
fwupd crashes on start when firmware.xml.xz is corrupted

### ISSUE THREAD

**Issue by marmarek** [fwupd/fwupd#5554]
**Describe the bug**
When /var/lib/fwupd/metadata/lvfs/metadata.xml.xz is corrupted, the service fails to start. Besides being a crash in itself, this prevents fixing the issue without manually modifying fwupd's files. Removing broken metadata.xml.xz "fixes" the problem.

**Steps to Reproduce**

1. Take fwupd-1.8.10-2.fc37.x86_64
2. Download `https://cdn.fwupd.org/downloads/firmware.xml.gz` and matching jcat (note it is **gz**, not **xz**, as an attempt to workaround https://gitlab.com/fwupd/lvfs-website/-/issues/860)
3. Call `fwupdagent refresh firmware.xml.gz firmware.xml.gz.jcat lvfs`

**Expected behavior**

fwupd logs an error about corrupted metadata file but otherwise starts normally (treating it as missing file probably?) allowing the user to fetch the correct one.

This is not a duplicate of https://github.com/fwupd/fwupd/issues/5553, it only happens to be triggered by the same steps. Service should not crash on start regardless of the reasons why metadata file got corrupted.

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version
compile   org.freedesktop.fwupd         1.8.10
compile   com.hughsie.libjcat           0.1.12
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.3
runtime   com.hughsie.libjcat           0.1.12
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.4.5
runtime   org.kernel                    6.1.12-1.qubes.fc37.x86_64
runtime   org.freedesktop.fwupd         1.8.10
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc): default package in Fedora 37

The crash:
```
fwupd[7640]: ERROR:../src/xb-lzma-decompressor.c:132:xb_lzma_decompressor_convert: code should not be reached
fwupd[7640]: Bail out! ERROR:../src/xb-lzma-decompressor.c:132:xb_lzma_decompressor_convert: code should not be reached

Stack trace of thread 7640:
#0  0x00007068343d4e5c __pthread_kill_implementation (libc.so.6 + 0x8ce5c)
#1  0x0000706834384a76 raise (libc.so.6 + 0x3ca76)
#2  0x000070683436e7fc abort (libc.so.6 + 0x267fc)
#3  0x0000706834564ef8 g_assertion_message.cold (libglib-2.0.so.0 + 0x1fef8)
#4  0x00007068345c58ae g_assertion_message_expr (libglib-2.0.so.0 + 0x808ae)
#5  0x0000706834c5b31b xb_lzma_decompressor_convert (libxmlb.so.2 + 0xd31b)
#6  0x00007068346d75be read_internal (libgio-2.0.so.0 + 0x525be)
#7  0x00007068347061c5 g_input_stream_read (libgio-2.0.so.0 + 0x811c5)
#8  0x0000706834c618d2 xb_builder_compile (libxmlb.so.2 + 0x138d2)
#9  0x0000706834c625ab xb_builder_ensure (libxmlb.so.2 + 0x145ab)
#10 0x0000706834a80d5a fu_engine_load_metadata_store (libfwupdengine.so + 0x80d5a)
#11 0x0000706834a8973f fu_engine_load (libfwupdengine.so + 0x8973f)
#12 0x000059f76acfa997 fu_daemon_setup (fwupd + 0xf997)
#13 0x000059f76acf3f4b main (fwupd + 0x8f4b)
#14 0x000070683436f510 __libc_start_call_main (libc.so.6 + 0x27510)
#15 0x000070683436f5c9 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x275c9)
#16 0x000059f76acf43d5 _start (fwupd + 0x93d5)
```

**Additional questions**

- Operating system and version: Fedora 37
- Have you tried rebooting? doesn't look relevant, but I did tried restarting fwupd service; it crashes on start
- Is this a regression? maybe?

**Comment by 3v1n0** [comment]
mhmh, I'm still getting this with 1.9.9:

```
ERROR:../src/xb-lzma-decompressor.c:130:xb_lzma_decompressor_convert: code should not be reached
Bail out! ERROR:../src/xb-lzma-decompressor.c:130:xb_lzma_decompressor_convert: code should not be reached

Thread 1 "fwupd" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737313229568) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: File o directory non esistente.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737313229568) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737313229568) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737313229568, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7442476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff74287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7743b57 in g_assertion_message
    (domain=<optimized out>, file=<optimized out>, line=<optimized out>, func=0x7ffff7eb4990 "xb_lzma_decompressor_convert", message=<optimized out>) at ../../../glib/gtestutils.c:3253
#6  0x00007ffff779d70f in g_assertion_message_expr
    (domain=0x0, file=0x7ffff7eb412e "../src/xb-lzma-decompressor.c", line=130, func=0x7ffff7eb4990 "xb_lzma_decompressor_convert", expr=<optimized out>) at ../../../glib/gtestutils.c:3279
#7  0x00007ffff7e9d548 in  () at /lib/x86_64-linux-gnu/libxmlb.so.2
#8  0x00007ffff78aeec5 in read_internal
    (stream=<optimized out>, buffer=<optimized out>, count=<optimized out>, blocking=1, cancellable=0x0, error=0x7fffffffdea8) at ../../../gio/gconverterinputstream.c:492
#9  0x00007ffff78dd1f7 in g_input_stream_read
    (stream=0x5555555b6960, buffer=0x55555566ce70, count=32768, cancellable=0x0, error=0x7fffffffdea8)
    at ../../../gio/ginputstream.c:198
#10 0x00007ffff7ea323c in xb_builder_compile () at /lib/x86_64-linux-gnu/libxmlb.so.2
#11 0x00007ffff7ea4165 in xb_builder_ensure () at /lib/x86_64-linux-gnu/libxmlb.so.2
#12 0x00007ffff7c8a249 in fu_engine_load_metadata_store
    (self=self@entry=0x5555555b2000, flags=flags@entry=78, error=error@entry=0x7fffffffe238)
    at ../src/fu-engine.c:4623
#13 0x00007ffff7c916e3 in fu_engine_load
    (self=<optimized out>, flags=flags@entry=78, progress=<optimized out>, error=error@entry=0x7fffffffe238)
    at ../src/fu-engine.c:8757
#14 0x0000555555561c92 in fu_daemon_setup
    (self=self@entry=0x5555555aa010, socket_address=socket_address@entry=0x0, error=error@entry=0x7fffffffe238)
    at ../src/fu-daemon.c:2306
#15 0x000055555555c078 in main (argc=<optimized out>, argv=<optimized out>) at ../src/fu-main.c:174
```
